apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deploy
spec:
   replicas: 3
   selector:
      matchLabels:
         app: nginx-sample
   template:
      metadata:
         labels:
            app: nginx-sample
      spec:
         containers:
           - name: k8scontainer
             image: munireddy1/k8simage:v1
             ports:
             - containerPort: 8000
               hostPort: 30011
