apiVersion: v1
kind: ReplicationController
metadata:
   name: nginx-rc
spec:
   replicas: 4
   selector:
      app: nginx-sample
   template:
      metadata:
         labels:
            app: nginx-sample
      spec:        
         containers:
           - name: k8scontainer
             image: munireddy1/k8simage:v1
             ports:
             - containerPort: 8000      
