apiVersion: v1
kind: Service
metadata:
   name: k8s-service
   labels:
      app: nginx-sample
spec:
   type: NodePort
   ports:
     - port: 8000
       nodePort: 30033
       protocol: TCP
   selector:
     app: nginx-sample
